= Boundary Devices BSP

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir boundary-bsp
$: cd boundary-bsp
$: repo init -u git://github.com/DigicoUK/boundary-bsp-platform -b pyro-spitfire-dev
$: repo sync

At the end of the commands you have every metadata you need to start work with.

To start a simple image build:

[source,console]
$: source ./setup-environment build
$: bitbake core-image-minimal

You can use any directory to host your build.

The source code is checked out at `boundary-bsp/sources`.

== Build the SDK:

[source,console]
$: repo init -u git://github.com/DigicoUK/boundary-bsp-platform -b pyro-spitfire-dev
$: repo sync
$: MACHINE=imx6qsabrelite DISTRO=fslc-framebuffer source setup-environment build

Then edit the `build/conf/local.conf` file and add the following line:

[source,shell]
PACKAGECONFIG_append_pn-qtbase = " sql-sqlite accessibility"

Then build the SDK:

[source,console]
$: time bitbake meta-toolchain-qt5

(Takes about 5-6 hours on quad core i5 and fast SSD which needs at least 80GB free space.)
